#!/bin/sh
# Enable all detected Wi-Fi radios/interfaces on first boot.
[ -x /sbin/uci ] || exit 0

for radio in $(uci show wireless 2>/dev/null | sed -n 's/^wireless\.(@wifi-device\[[0-9][0-9]*\])\.disabled=.*/\1/p' | sort -u); do
	uci set wireless.$radio.disabled='0'
done

for iface in $(uci show wireless 2>/dev/null | sed -n 's/^wireless\.(@wifi-iface\[[0-9][0-9]*\])\.disabled=.*/\1/p' | sort -u); do
	uci set wireless.$iface.disabled='0'
done

uci commit wireless 2>/dev/null || true
exit 0
